--DROP TABLE Col_Serach;
--DROP TABLE Data_Type;

CREATE VOLATILE TABLE Col_Serach
(
 part_of_the_string VARCHAR(50) NOT NULL
) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE Data_Type
(
 Code VARCHAR(2) NULL,
 FullForm VARCHAR(100) NULL,
 DType VARCHAR(50) NULL
) ON COMMIT PRESERVE ROWS;

INSERT INTO Col_Serach
(part_of_the_string)
SELECT token
  FROM TABLE (StrTok_Split_To_Table('string1', 'Item_Identifier', '_')
RETURNS (outkey VARCHAR(10) CHARACTER SET Unicode
        ,tokennum INTEGER
        ,token VARCHAR(50) CHARACTER SET Unicode)
        ) AS dt;

INSERT INTO Data_Type
SELECT '++', 'TD_ANYTYPE', 'TD_ANYTYPE';
INSERT INTO Data_Type
SELECT 'A1', 'ARRAY (one dimensional)', 'ARRAY';
INSERT INTO Data_Type
SELECT 'AN', 'ARRAY (multidimensional)', 'MULTI-DIMENSIONAL ARRAY';
INSERT INTO Data_Type
SELECT 'I8', 'BIGINT', 'BIGINT';
INSERT INTO Data_Type
SELECT 'BO', 'BINARY LARGE OBJECT', 'BLOB';
INSERT INTO Data_Type
SELECT 'BF', 'BYTE', 'BYTE';
INSERT INTO Data_Type
SELECT 'BV', 'BYTE VARYING', 'VARBYTE';
INSERT INTO Data_Type
SELECT 'I1', 'BYTEINT', 'BYTEINT';
INSERT INTO Data_Type
SELECT 'CF', 'CHARACTER (fixed)', 'CHAR';
INSERT INTO Data_Type
SELECT 'CV', 'CHARACTER (varying)', 'VARCHAR';
INSERT INTO Data_Type
SELECT 'CO', 'CHARACTER LARGE OBJECT', 'CLOB';
INSERT INTO Data_Type
SELECT 'D', 'DECIMAL', 'DECIMAL';
INSERT INTO Data_Type
SELECT 'DA', 'DATE', 'DATE';
INSERT INTO Data_Type
SELECT 'F', 'FLOAT; FLOAT, DOUBLE PRECISION, and REAL are different names for the same data type.', 'FLOAT';
INSERT INTO Data_Type
SELECT 'I', 'INTEGER', 'INTEGER';
INSERT INTO Data_Type
SELECT 'DY', 'INTERVAL DAY', 'INTERVAL DAY';
INSERT INTO Data_Type
SELECT 'DH', 'INTERVAL DAY TO HOUR', 'INTERVAL DAY TO HOUR';
INSERT INTO Data_Type
SELECT 'DM', 'INTERVAL DAY TO MINUTE', 'INTERVAL DAY TO MINUTE';
INSERT INTO Data_Type
SELECT 'DS', 'INTERVAL DAY TO SECOND', 'INTERVAL DAY TO SECOND';
INSERT INTO Data_Type
SELECT 'HR', 'INTERVAL HOUR', 'INTERVAL HOUR';
INSERT INTO Data_Type
SELECT 'HM', 'INTERVAL HOUR TO MINUTE', 'INTERVAL HOUR TO MINUTE';
INSERT INTO Data_Type
SELECT 'HS', 'INTERVAL HOUR TO SECOND', 'INTERVAL HOUR TO SECOND';
INSERT INTO Data_Type
SELECT 'MI', 'INTERVAL MINUTE', 'INTERVAL MINUTE';
INSERT INTO Data_Type
SELECT 'MS', 'INTERVAL MINUTE TO SECOND', 'INTERVAL MINUTE TO SECOND';
INSERT INTO Data_Type
SELECT 'MO', 'INTERVAL MONTH', 'INTERVAL MONTH';
INSERT INTO Data_Type
SELECT 'SC', 'INTERVAL SECOND', 'INTERVAL SECOND';
INSERT INTO Data_Type
SELECT 'YR', 'INTERVAL YEAR', 'INTERVAL SECOND';
INSERT INTO Data_Type
SELECT 'YM', 'INTERVAL YEAR TO MONTH', 'INTERVAL YEAR TO MONTH';
INSERT INTO Data_Type
SELECT 'N', 'NUMBER', 'NUMBER';
INSERT INTO Data_Type
SELECT 'D', 'NUMERIC', 'NUMERIC';
INSERT INTO Data_Type
SELECT 'PD', 'PERIOD(DATE)', 'PERIOD(DATE)';
INSERT INTO Data_Type
SELECT 'PT', 'PERIOD(TIME(n))', 'PERIOD(TIME)';
INSERT INTO Data_Type
SELECT 'PZ', 'PERIOD(TIME(n) WITH TIME ZONE)', 'PERIOD(TIME WITH TIME ZONE)';
INSERT INTO Data_Type
SELECT 'PS', 'PERIOD(TIMESTAMP(n))', 'PERIOD(TIMESTAMP)';
INSERT INTO Data_Type
SELECT 'PM', 'PERIOD(TIMESTAMP(n) WITH TIME ZONE)', 'PERIOD(TIMESTAMP WITH TIME ZONE)';
INSERT INTO Data_Type
SELECT 'I2', 'SMALLINT', 'SMALLINT';
INSERT INTO Data_Type
SELECT 'AT', 'TIME', 'TIME';
INSERT INTO Data_Type
SELECT 'TS', 'TIMESTAMP', 'TIMESTAMP';
INSERT INTO Data_Type
SELECT 'TZ', 'TIME WITH TIME ZONE', 'TIME WITH TIME ZONE';
INSERT INTO Data_Type
SELECT 'SZ', 'TIMESTAMP WITH TIME ZONE', 'TIMESTAMP WITH TIME ZONE';
INSERT INTO Data_Type
SELECT 'UT', 'USER-DEFINED TYPE (ALL types)', 'UDT Type';
INSERT INTO Data_Type
SELECT 'XM', 'XML', 'XML';

--SELECT * FROM Col_Serach;
--SELECT * FROM Data_Type;

SELECT DatabaseName, TableName, ColumnName, part_of_the_string, DType, ColumnLength, Nullable
  FROM DBC.ColumnsV
       INNER JOIN Col_Serach ON ColumnName LIKE Coalesce(Concat('%', part_of_the_string, '%'), ColumnName)
	   INNER JOIN Data_Type ON Coalesce(ColumnType, '') = Code
 WHERE 1 = 1
   --AND DatabaseName = ''
   --AND TableName = ''
   --AND ColumnName LIKE '%%'
 ORDER BY ColumnName, DatabaseName, TableName;